import React, { Component } from 'react'

export default class Home extends Component {
  render() {
    return (
      <h3>DO YOU HAVE AN APARTMENT FOR RENT? ARE OFFERING COMPETIIVE PRICES? IS YOUR APARTMENT BEAUTIFUL? IF YOU ANSWER YES TO ANY OF THESE QUESTIONS THEN BIGBODYAPARTMENTS IS THE PLACE FOR YOU! HERE AT BIGBODYAPARTMENTS WE OFFER VARIETY OF LUXARY APARTMENTS AT AFFORDABLE PRICES!  </h3>
    )
  }
}
